# Generated by Django 4.2.30 on 2026-05-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0011_remove_bugreport_assignees_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="UserCalendarSettings",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "caldav_url",
                            models.URLField(default="http://localhost:5232/", max_length=500),
                        ),
                        (
                            "caldav_user",
                            models.CharField(
                                blank=True, default="your_username", max_length=100, null=True
                            ),
                        ),
                        (
                            "caldav_password",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "caldav_calendar_name",
                            models.CharField(default="IIAP OM", max_length=100),
                        ),
                        (
                            "google_calendar_id",
                            models.CharField(default="primary", max_length=255),
                        ),
                        ("google_oauth_token", models.JSONField(blank=True, null=True)),
                        ("is_google_synced", models.BooleanField(default=False)),
                        ("is_caldav_synced", models.BooleanField(default=False)),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="calendar_settings",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_usercalendarsettings",
                    },
                ),
                migrations.CreateModel(
                    name="CalendarEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=200)),
                        ("description", models.TextField(blank=True)),
                        (
                            "event_type",
                            models.CharField(
                                choices=[
                                    ("milestone", "Milestone"),
                                    ("meeting", "Meeting"),
                                    ("deadline", "Deadline"),
                                    ("review", "Review"),
                                    ("other", "Other"),
                                ],
                                default="other",
                                max_length=20,
                            ),
                        ),
                        ("start_datetime", models.DateTimeField()),
                        ("end_datetime", models.DateTimeField()),
                        (
                            "meeting_link",
                            models.URLField(blank=True, max_length=500, null=True),
                        ),
                        (
                            "meeting_password",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "location",
                            models.CharField(
                                blank=True,
                                help_text="Physical location or room",
                                max_length=300,
                                null=True,
                            ),
                        ),
                        ("color", models.CharField(default="#6366f1", max_length=7)),
                        (
                            "google_event_id",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        (
                            "caldav_event_path",
                            models.CharField(blank=True, max_length=500, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "attendees",
                            models.ManyToManyField(
                                blank=True,
                                related_name="calendar_events",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="tasks.project",
                            ),
                        ),
                        (
                            "task",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="tasks.task",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_calendarevent",
                        "ordering": ["start_datetime"],
                    },
                ),
            ]
        )
    ]
