# Generated by Django 4.2.30 on 2026-06-03 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_hub", "0002_repoactivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are collaborators and have write access to this repository.",
                related_name="collaborating_repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If checked, only the owner, collaborators, and admins can access this repository.",
            ),
        ),
    ]
