# Generated by Django 4.2.30 on 2026-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatclear"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="room_picture",
            field=models.ImageField(blank=True, null=True, upload_to="room_avatars/"),
        ),
    ]
