# Generated by Django 4.2.30 on 2026-05-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_access_adjustments_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_alerts_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_limits_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_pm",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_rentals_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_serials_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_shortage_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_access_telescope",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_add_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_approve_transfer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_delete_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_edit_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_export_reports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_adjustments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_limits",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_rentals",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_serials",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_shortage_exports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_users",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_all_branches_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="inventory_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_users",
                to="inventory.branch",
            ),
        ),
    ]
