# Generated by Django 4.2.30 on 2026-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_access_pm",
            field=models.BooleanField(default=True),
        ),
    ]
