# Generated by Django 4.2.30 on 2026-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_can_access_adjustments_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_command_dome",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_operate_cassegrain",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_operate_jcbt",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_operate_schmidt",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_operate_vbt",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_operate_zeiss",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="can_trigger_exposures",
            field=models.BooleanField(default=True),
        ),
    ]
