# Generated by Django 4.2.30 on 2026-05-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_can_access_adjustments_page_and_more"),
    ]

    operations = [
        # Telescope fields removed — no operations needed
    ]
