# Generated by Django 4.2.30 on 2026-05-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_can_command_dome_user_can_operate_cassegrain_and_more"),
    ]

    operations = [
        # is_telescope_admin field removed — no operations needed
    ]
