# Generated by Django 6.0.6 on 2026-06-23 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_telescope_admin"),
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_color",
            field=models.CharField(
                default="#6366f1",
                help_text="Hex code of the color theme representing the user avatar.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_adjustments_page",
            field=models.BooleanField(
                default=True, help_text="Allows viewing the stock adjustments list."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_alerts_page",
            field=models.BooleanField(
                default=True,
                help_text="Allows viewing inventory reorder and expiry alerts.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_inventory",
            field=models.BooleanField(
                default=False,
                help_text="Allows access to the Inventory Management System.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_limits_page",
            field=models.BooleanField(
                default=True,
                help_text="Allows viewing minimum stock thresholds/reorder limits.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_pm",
            field=models.BooleanField(
                default=True,
                help_text="Allows access to the Project Management System.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_rentals_page",
            field=models.BooleanField(
                default=True, help_text="Allows viewing tool/item rentals."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_serials_page",
            field=models.BooleanField(
                default=True, help_text="Allows viewing the serial tracking page."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_shortage_page",
            field=models.BooleanField(
                default=True, help_text="Allows viewing lists of out-of-stock items."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_telescope",
            field=models.BooleanField(
                default=False,
                help_text="Allows access to the Telescope Control System.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_add_inventory",
            field=models.BooleanField(
                default=True, help_text="Allows adding new stock items."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_approve_transfer",
            field=models.BooleanField(
                default=True,
                help_text="Allows approving stock transfers between branches.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_command_dome",
            field=models.BooleanField(
                default=True,
                help_text="Allows opening/closing and rotation commands to the dome structure.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_delete_inventory",
            field=models.BooleanField(
                default=True, help_text="Allows archiving/deleting stock records."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_edit_inventory",
            field=models.BooleanField(
                default=True,
                help_text="Allows modifying details of existing stock items.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_export_reports",
            field=models.BooleanField(
                default=True,
                help_text="Allows generating inventory stock status PDF/CSV reports.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_adjustments",
            field=models.BooleanField(
                default=True,
                help_text="Allows creating or modifying stock adjustments.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Allows clearing or modifying alerts configurations.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_limits",
            field=models.BooleanField(
                default=True, help_text="Allows setting/modifying reorder points."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_rentals",
            field=models.BooleanField(
                default=True,
                help_text="Allows renting out items or checking them back in.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_serials",
            field=models.BooleanField(
                default=True,
                help_text="Allows registering or editing serial/lot numbers.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_shortage_exports",
            field=models.BooleanField(
                default=True,
                help_text="Allows downloading Excel/CSV exports of shortage/purchase lists.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_users",
            field=models.BooleanField(
                default=True, help_text="Allows administrating inventory system users."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_operate_cassegrain",
            field=models.BooleanField(
                default=True,
                help_text="Allows operation commands on the Cassegrain Spectrograph.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_operate_jcbt",
            field=models.BooleanField(
                default=True,
                help_text="Allows operation commands on the JC Bhattacharya Telescope (JCBT).",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_operate_schmidt",
            field=models.BooleanField(
                default=True,
                help_text="Allows operation commands on the Schmidt Telescope.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_operate_vbt",
            field=models.BooleanField(
                default=True,
                help_text="Allows operation commands on the Vainu Bappu Telescope (VBT).",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_operate_zeiss",
            field=models.BooleanField(
                default=True,
                help_text="Allows operation commands on the Zeiss Telescope.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_trigger_exposures",
            field=models.BooleanField(
                default=True,
                help_text="Allows triggering science CCD exposures or taking calibrations.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_view_all_branches_inventory",
            field=models.BooleanField(
                default=True,
                help_text="Allows viewing stock counts across other branches.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Datetime when the user profile was originally created.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="User's professional title/designation.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Toggle to receive email updates and alerts from the system.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="inventory_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated inventory warehouse branch for stock and transfers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_users",
                to="inventory.branch",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user account is active. Deselect instead of deleting.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_telescope_admin",
            field=models.BooleanField(
                default=False,
                help_text="Allows administrative configurations in the Telescope app.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Optional nickname or display moniker.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact telephone/mobile number.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile picture image file.",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("project_manager", "Project Manager"),
                    ("member", "Member"),
                    ("student", "Student"),
                ],
                default="member",
                help_text="Defines user level permissions within Project Management.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("mechanical", "Mechanical"),
                    ("optics", "Optics"),
                    ("simulation", "Simulation"),
                    ("software", "Software"),
                    ("general", "General"),
                ],
                default="general",
                help_text="Specifies the functional module or department team.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                default="light",
                help_text="Dashboard UI theme preference (e.g., light, dark, night).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datetime when the user profile was last updated.",
            ),
        ),
    ]
