# Generated by Django 6.0.6 on 2026-06-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_telescope_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_color",
            field=models.CharField(
                default="#6366f1",
                help_text="Hex code of the color theme representing the user avatar.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_access_pm",
            field=models.BooleanField(
                default=True,
                help_text="Allows access to the Project Management System.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Datetime when the user profile was originally created.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                blank=True,
                help_text="User's professional title/designation.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Toggle to receive email updates and alerts from the system.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user account is active. Deselect instead of deleting.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="Optional nickname or display moniker.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact telephone/mobile number.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile picture image file.",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("project_manager", "Project Manager"),
                    ("member", "Member"),
                    ("student", "Student"),
                ],
                default="member",
                help_text="Defines user level permissions within Project Management.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("mechanical", "Mechanical"),
                    ("optics", "Optics"),
                    ("simulation", "Simulation"),
                    ("software", "Software"),
                    ("general", "General"),
                ],
                default="general",
                help_text="Specifies the functional module or department team.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                default="light",
                help_text="Dashboard UI theme preference (e.g., light, dark, night).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Datetime when the user profile was last updated.",
            ),
        ),
    ]
