# Generated by Django 6.0.6 on 2026-06-23 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inv_messages', to='inventory.inventoryuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inv_messages', to='inventory.inventoryuser')),
            ],
            options={
                'verbose_name': 'Inventory Message',
                'verbose_name_plural': 'Inventory Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
