# Generated by Django 4.2.30 on 2026-05-12 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0003_knowledgebasenote_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcase",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_test_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="is_in_trash",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="story_points",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
