# Generated by Django 4.2.30 on 2026-05-14 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_testcase_deleted_at_testcase_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugreport",
            name="resolution_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bugreport",
            name="resolution_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bugreport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_bugs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bugreport",
            name="solving_results",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("publish", "Publish"),
                    ("restore", "Restore"),
                    ("upload", "Upload"),
                    ("download", "Download"),
                    ("move", "Move"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="module",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("requirement", "Requirement"),
                    ("task", "Task"),
                    ("test_case", "Test Case"),
                    ("bug", "Bug Report"),
                    ("release", "Release"),
                    ("user", "User Management"),
                    ("system", "System Settings"),
                    ("file", "File"),
                    ("folder", "Folder"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BugComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="bugs/comments/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tasks.bugreport",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
