# Generated by Django 4.2.30 on 2026-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_bugreport_resolution_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugreport",
            name="resolution_attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="bugs/resolutions/%Y/%m/"
            ),
        ),
    ]
