# Generated by Django 4.2.30 on 2026-05-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_bugreport_resolution_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="linked_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_bugs",
                to="tasks.task",
            ),
        ),
    ]
