# Generated by Django 4.2.30 on 2026-05-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_alter_documentaccessright_kb_note"),
        ("tasks", "0009_alter_notification_notification_type"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="KnowledgeBaseNote",
                ),
            ],
            database_operations=[],
        )
    ]
