# Generated by Django 4.2.30 on 2026-05-31 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_comment_parent_moduleforumpost_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGitPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_message', models.TextField(blank=True)),
                ('commit_hash', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('remote_url', models.CharField(blank=True, max_length=500)),
                ('files_pushed', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_push_logs', to='tasks.project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_push_logs', to='tasks.release')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_url', models.CharField(help_text='e.g. git@github.com:org/repo.git or https://github.com/org/repo.git', max_length=500)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('auth_method', models.CharField(choices=[('ssh_key', 'SSH Private Key'), ('https_token', 'HTTPS / Personal Access Token')], default='ssh_key', max_length=20)),
                ('git_username', models.CharField(blank=True, help_text='Git author username (used in commits)', max_length=200)),
                ('git_email', models.CharField(blank=True, help_text='Git author e-mail (used in commits)', max_length=200)),
                ('_ssh_private_key_enc', models.TextField(blank=True, db_column='ssh_private_key_enc')),
                ('_https_token_enc', models.TextField(blank=True, db_column='https_token_enc')),
                ('https_username', models.CharField(blank=True, max_length=200)),
                ('release_dir', models.CharField(blank=True, default='', help_text='Optional sub-directory inside the repo where release files are committed. Leave blank for root.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_configs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git_config', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Project Git Configuration',
            },
        ),
    ]
