# Generated by Django 4.2.30 on 2026-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_git_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgitpushlog",
            name="terminal_output",
            field=models.TextField(blank=True, default=""),
        ),
    ]
