# Generated by Django 4.2.30 on 2026-06-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_projectgitpushlog_terminal_output"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="release_requested",
        ),
        migrations.RemoveField(
            model_name="project",
            name="release_requested_at",
        ),
    ]
