# Generated by Django 4.2.30 on 2026-06-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_remove_project_release_requested_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectgitpushlog",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectgitpushlog",
            name="release",
        ),
        migrations.RemoveField(
            model_name="projectgitpushlog",
            name="triggered_by",
        ),
        migrations.DeleteModel(
            name="ProjectGitConfig",
        ),
        migrations.DeleteModel(
            name="ProjectGitPushLog",
        ),
    ]
