# Generated by Django 4.2.30 on 2026-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Telescope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_name",
                    models.CharField(
                        help_text="Short identifier, e.g., vbt_234",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "aperture",
                    models.CharField(help_text="e.g., 2.34 Meter", max_length=50),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="e.g., Reflector (Cassegrain / Prime Focus)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("observing", "Observing"),
                            ("idle", "Idle / Ready"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "current_target",
                    models.CharField(blank=True, default="None", max_length=200),
                ),
                (
                    "ra",
                    models.CharField(blank=True, default="00h 00m 00s", max_length=50),
                ),
                (
                    "dec",
                    models.CharField(blank=True, default="+00° 00′ 00″", max_length=50),
                ),
                (
                    "dome",
                    models.CharField(
                        default="Closed", help_text="Open or Closed", max_length=20
                    ),
                ),
                (
                    "focus",
                    models.CharField(blank=True, default="Cassegrain", max_length=50),
                ),
                (
                    "instrument",
                    models.CharField(blank=True, default="None", max_length=100),
                ),
                (
                    "ccd_temp",
                    models.CharField(blank=True, default="Ambient", max_length=50),
                ),
                (
                    "tracking",
                    models.CharField(
                        default="Disabled",
                        help_text="Enabled or Disabled",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="telescopes/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="External image URL fallback",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed information and specifications from VBO site",
                    ),
                ),
                (
                    "history",
                    models.TextField(blank=True, help_text="Historical details"),
                ),
            ],
        ),
    ]
