# Generated by Django 4.2.30 on 2026-05-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0011_remove_bugreport_assignees_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="TestCase",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "test_id",
                            models.CharField(blank=True, max_length=50, null=True, unique=True),
                        ),
                        ("title", models.CharField(max_length=300)),
                        ("scenario", models.TextField(blank=True)),
                        ("preconditions", models.TextField(blank=True)),
                        ("steps", models.TextField(blank=True)),
                        ("expected_result", models.TextField(blank=True)),
                        ("actual_result", models.TextField(blank=True)),
                        (
                            "priority",
                            models.CharField(
                                choices=[
                                    ("low", "Low"),
                                    ("medium", "Medium"),
                                    ("high", "High"),
                                    ("critical", "Critical"),
                                ],
                                default="medium",
                                max_length=10,
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending Verification"),
                                    ("passed", "Passed"),
                                    ("failed", "Failed"),
                                    ("blocked", "Blocked"),
                                    ("retest", "Needs Re-test"),
                                ],
                                default="pending",
                                max_length=20,
                            ),
                        ),
                        ("verified_date", models.DateTimeField(blank=True, null=True)),
                        (
                            "approval_status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("approved", "Approved"),
                                    ("rejected", "Rejected"),
                                ],
                                default="pending",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_in_trash", models.BooleanField(default=False)),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "assigned_members",
                            models.ManyToManyField(
                                blank=True,
                                related_name="assigned_test_cases",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="created_test_cases",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "deleted_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="deleted_test_cases",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="test_cases",
                                to="tasks.project",
                            ),
                        ),
                        (
                            "task",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="test_cases",
                                to="tasks.task",
                            ),
                        ),
                        (
                            "verified_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="verified_test_cases",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_testcase",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="TestCaseHistory",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("action", models.CharField(max_length=50)),
                        ("details", models.TextField(blank=True)),
                        ("timestamp", models.DateTimeField(auto_now_add=True)),
                        (
                            "test_case",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="history",
                                to="testcases.testcase",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_testcasehistory",
                        "ordering": ["-timestamp"],
                    },
                ),
                migrations.CreateModel(
                    name="TestCaseAttachment",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("file", models.FileField(upload_to="test_cases/attachments/%Y/%m/")),
                        ("description", models.CharField(blank=True, max_length=255)),
                        ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "test_case",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="attachments",
                                to="testcases.testcase",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_testcaseattachment",
                    },
                ),
            ]
        )
    ]
