# Generated by Django 4.2.30 on 2026-05-12 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="admin_approved_deletion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="hidden_from_user_trash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="is_in_trash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="pm_approved_deletion",
            field=models.BooleanField(default=False),
        ),
    ]
