# Generated by Django 4.2.30 on 2026-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_projectfile_admin_approved_deletion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_file_size_gb",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum file upload size in GB (Max 10GB)",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
