# Generated by Django 4.2.30 on 2026-05-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "__first__"),
        ("files", "0005_filecategory_deleted_at_filecategory_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentaccessright",
            name="kb_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_rights",
                to="notes.knowledgebasenote",
            ),
        ),
    ]
