# Generated by Django 4.2.30 on 2026-05-26 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0006_alter_documentaccessright_kb_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecomment",
            name="annotation_coords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="highlight_color",
            field=models.CharField(default="#ffeb3b", max_length=50),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="files.filecomment",
            ),
        ),
        migrations.AddField(
            model_name="filecomment",
            name="section",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
