# Generated by Django 4.2.30 on 2026-05-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_filecomment_annotation_coords_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecomment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="files.filecategory",
            ),
        ),
        migrations.AlterField(
            model_name="filecomment",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="files.projectfile",
            ),
        ),
    ]
