# Generated by Django 6.0.6 on 2026-06-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0008_filecomment_category_alter_filecomment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="max_file_size_gb",
            field=models.PositiveIntegerField(
                default=10, help_text="Maximum file upload size in GB (Max 50GB)"
            ),
        ),
    ]
