# Generated by Django 6.0.6 on 2026-06-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_systemsettings_max_file_size_gb'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filecategory',
            unique_together=set(),
        ),
    ]
