# Generated by Django 4.2.30 on 2026-05-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0011_remove_bugreport_assignees_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Notification",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "notification_type",
                            models.CharField(
                                choices=[
                                    ("task_assigned", "Task Assigned"),
                                    ("task_updated", "Task Updated"),
                                    ("task_completed", "Task Completed"),
                                    ("comment_added", "Comment Added"),
                                    ("due_soon", "Due Soon"),
                                    ("overdue", "Overdue"),
                                    ("project_update", "Project Update"),
                                    ("test_assigned", "Test Case Assigned"),
                                    ("test_failed", "Test Case Failed"),
                                    ("test_approved", "Test Case Approved"),
                                    ("retest_requested", "Re-test Requested"),
                                    ("task_ready_completion", "Task Ready for Completion"),
                                    ("chat_message", "New Chat Message"),
                                    ("bug_reported", "Bug Reported"),
                                ],
                                max_length=30,
                            ),
                        ),
                        ("title", models.CharField(max_length=200)),
                        ("message", models.TextField()),
                        ("is_read", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="tasks.project",
                            ),
                        ),
                        (
                            "recipient",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="notifications",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "sender",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="sent_notifications",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "task",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="tasks.task",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_notification",
                        "ordering": ["-created_at"],
                    },
                ),
            ]
        )
    ]
