# Generated by Django 4.2.30 on 2026-06-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("task_updated", "Task Updated"),
                    ("task_completed", "Task Completed"),
                    ("comment_added", "Comment Added"),
                    ("due_soon", "Due Soon"),
                    ("overdue", "Overdue"),
                    ("project_update", "Project Update"),
                    ("test_assigned", "Test Case Assigned"),
                    ("test_failed", "Test Case Failed"),
                    ("test_approved", "Test Case Approved"),
                    ("retest_requested", "Re-test Requested"),
                    ("task_ready_completion", "Task Ready for Completion"),
                    ("chat_message", "New Chat Message"),
                    ("bug_reported", "Bug Reported"),
                    ("repo_invite", "Repository Invitation"),
                ],
                max_length=30,
            ),
        ),
    ]
