# Generated by Django 4.2.30 on 2026-05-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0011_remove_bugreport_assignees_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="BugReport",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=300)),
                        ("description", models.TextField()),
                        (
                            "severity",
                            models.CharField(
                                choices=[
                                    ("low", "Low"),
                                    ("medium", "Medium"),
                                    ("high", "High"),
                                    ("critical", "Critical"),
                                ],
                                default="medium",
                                max_length=10,
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("open", "Open"),
                                    ("in_progress", "In Progress"),
                                    ("resolved", "Resolved"),
                                    ("closed", "Closed"),
                                    ("wont_fix", "Won't Fix"),
                                ],
                                default="open",
                                max_length=20,
                            ),
                        ),
                        ("steps_to_reproduce", models.TextField(blank=True)),
                        ("expected_behavior", models.TextField(blank=True)),
                        ("actual_behavior", models.TextField(blank=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_in_trash", models.BooleanField(default=False)),
                        ("deleted_at", models.DateTimeField(blank=True, null=True)),
                        ("resolution_summary", models.TextField(blank=True)),
                        ("solving_results", models.TextField(blank=True)),
                        (
                            "resolution_attachment",
                            models.FileField(
                                blank=True, null=True, upload_to="bugs/resolutions/%Y/%m/"
                            ),
                        ),
                        ("resolution_date", models.DateTimeField(blank=True, null=True)),
                        (
                            "assignees",
                            models.ManyToManyField(
                                blank=True,
                                related_name="assigned_bugs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "deleted_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="deleted_bugs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "linked_task",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="linked_bugs",
                                to="tasks.task",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="bug_reports",
                                to="tasks.project",
                            ),
                        ),
                        (
                            "reported_by",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="reported_bugs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "resolved_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="resolved_bugs",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_bugreport",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="BugComment",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("content", models.TextField()),
                        (
                            "attachment",
                            models.FileField(
                                blank=True, null=True, upload_to="bugs/comments/%Y/%m/"
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "author",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "bug",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="comments",
                                to="bugs.bugreport",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tasks_bugcomment",
                        "ordering": ["created_at"],
                    },
                ),
            ]
        )
    ]
