# Generated by Django 4.2.30 on 2026-05-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="bugs.bugcomment",
            ),
        ),
    ]
