# Generated by Django 6.0.6 on 2026-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_product_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
